# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

variables:
  imageName: 'pipelines-javascript-docker'


steps:
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    repository: $(imageName)
    command: build
    tags: latest
    Dockerfile: app/Dockerfile

- script: |
   echo "List Docker Images"
   docker images
  displayName: List Docker Images

- script: |
    docker save -o $(Build.ArtifactStagingDirectory)/$(imageName).tar $(imageName):latest
  displayName: Save the image
